---
title: "Research"
---

### Current Projects

1. #### Interest Rates, Innovation, and Creative Destruction
###### with Jonathan Goldberg and David-López-Salido.

Abstract: Do very low interest rates harm innovation, long-run growth, and competition? Using a quantitative endogenous growth model, we find that a lower interest rate boosts growth with the markup distribution little changed. Our framework nests canonical assumptions about creative destruction and the technology of R&D. To match the cross section of markups, profit volatility, R&D, and innovation output, as well as entrants' employment share and contribution to aggregate innovation, the model requires some "advantage of backwardness," with market laggards or entrants always having at least some chance of more-than-incremental innovation. A lower interest rate spurs innovation by raising the value of the profits from innovation; in general equilibrium, strategic interactions among firms and a rise in the wage dampen, but do not overturn, the valuation-driven increase in R&D and growth. To be sure, imposing severe (and counterfactual) restrictions on creative destruction leads to a growth "speed limit" at low interest rates, with growth declining as the interest rate falls. However, this decline in growth reverses under modest departures from these severe restrictions, if labor supply is elastic, if patent policy is adjusted optimally, or if credit access is restricted. The growth speed-limit economy offers policymakers a free lunch: weakening patent protection boosts growth and reduces markup-related production distortions. Our results suggest that very low interest rates do not harm growth and competition unless the forces of creative destruction are unrealistically shackled.

### Co-authors
1. [Jonathan Goldberg](https://scholar.google.com/citations?user=WOBQhOwAAAAJ&hl=en)
2. [David López-Salido](https://scholar.google.com/citations?user=iaDKz_0AAAAJ&hl=en)